Comparing files GUAM\TEST\AID.BAL and RT\GUAM\TEST\SAVE\AID.BAL
***** GUAM\TEST\AID.BAL
*MCALL #=     2 LV= 1          STFSMODE ON,INITIAL=YES
         DS    0H
*MEXIT #=     2 LV= 1 STFSMODE
***** RT\GUAM\TEST\SAVE\AID.BAL
*MCALL #=     2 LV= 1          STFSMODE ON,INITIAL=YES
       DS    0H
*MEXIT #=     2 LV= 1 STFSMODE
*****

***** GUAM\TEST\AID.BAL
*MCALL #=     3 LV= 1          STTMPMD ON
         DS    0H
*MEXIT #=     3 LV= 1 STTMPMD
***** RT\GUAM\TEST\SAVE\AID.BAL
*MCALL #=     3 LV= 1          STTMPMD ON
       DS    0H
*MEXIT #=     3 LV= 1 STTMPMD
*****

***** GUAM\TEST\AID.BAL
*MCALL #=     6 LV= 1          STLINENO LINE=1
         DS    0H
*MEXIT #=     6 LV= 1 STLINENO
***** RT\GUAM\TEST\SAVE\AID.BAL
*MCALL #=     6 LV= 1          STLINENO LINE=1
       DS    0H
*MEXIT #=     6 LV= 1 STLINENO
*****

***** GUAM\TEST\AID.BAL
*MCALL #=     7 LV= 1          STFSMODE OFF
         DS    0H
*MEXIT #=     7 LV= 1 STFSMODE
***** RT\GUAM\TEST\SAVE\AID.BAL
*MCALL #=     7 LV= 1          STFSMODE OFF
       DS    0H
*MEXIT #=     7 LV= 1 STFSMODE
*****

***** GUAM\TEST\AID.BAL
*MCALL #=     8 LV= 1          STTMPMD OFF
         DS    0H
*MEXIT #=     8 LV= 1 STTMPMD
***** RT\GUAM\TEST\SAVE\AID.BAL
*MCALL #=     8 LV= 1          STTMPMD OFF
       DS    0H
*MEXIT #=     8 LV= 1 STTMPMD
*****

